### ISSUE TITLE
Cannot start a container

### ISSUE THREAD

**Issue by mandrag0ra** [CenturyLinkLabs/panamax-ui#310]
Hi,

I tried to start a container but logs keep on this loop :

```
Aug 20 09:17:42 systemd jwilder_nginx-proxy_latest.service: control process exited, code=exited status=1
Aug 20 09:17:42 docker Error response from daemon: No such container: jwilder_nginx-proxy_latest

Aug 20 09:17:42 docker 2014/08/20 07:17:42 Error: failed to remove one or more containers

Aug 20 09:17:42 systemd Unit jwilder_nginx-proxy_latest.service entered failed state. 
```

But the container does exist. I can start it from command line.
Same after editing the "application" and rebooting the system.
Thanks.

**Comment by cosmoras** [comment]
Hello , same problem with same specific image - dockerfile..
I don't think it is due to size / download speed.
It must be something misconfigured. Please try to reproduce it , as a solution will strengthen
 underlying mechanisms to handle such cases.
How about if a manual deployment will docker on this one. Will it be possible for panamax to see it
 and include ti to an application structure and link it with other containers? 
Is there a work around? 

Regards
